# -*- coding: utf-8 -*-
"""use_model_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NW9K_JWofnTbYMYN-ki3QBa8aQ8AhQV_
"""

import numpy as np

import pickle

!ls

!wget https://github.com/futurexskill/ml-model-deployment/raw/main/classifier.pickle

!ls

!wget https://github.com/futurexskill/ml-model-deployment/raw/main/sc.pickle

!ls

classifier_colab = pickle.load(open('classifier.pickle','rb'))

scaler_colab = pickle.load(open('sc.pickle','rb'))

new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40,20000]])))

new_pred

new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40,20000]])))[:,1]
new_pred_proba

new_pred_2 = classifier_colab.predict(scaler_colab.transform(np.array([[42,50000]])))
new_pred_proba_2 = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42,50000]])))[:,1]
new_pred_2

new_pred_proba_2

