# -*- coding: utf-8 -*-
"""tf_data_types.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yj1MWbfGzu1J_bwwPq9s9AQ2GoFP3_5R
"""

!python --version

import tensorflow as tf

tf.__version__

"""Tensorflow has two data types - Tensor and Variable"""

tf.constant(10)

tf_const = tf.constant([10,20])

tf_const

tf_const.numpy()

var1 = tf_const.numpy()
var1

tensor1 = tf.convert_to_tensor(var1)

tensor1

x_2d_tensor = tf.constant([[10,20,30],[40,50,60]])
x_2d_tensor

x_zero_tensor = tf.zeros([3,4])
x_zero_tensor

x_ones_tensor = tf.ones([2,3])
x_ones_tensor

x_2d_tensor

tf.reshape(x_2d_tensor,[3,2])

"""Variable - can be modified"""

tf_var = tf.Variable([[10,20,30],[40,50,60]])

tf_var

tf_var.assign([[100,200,300],[400,500,600]])

tf_var[1,2].assign(0)

tf_var.assign_add([[10,20,300],[4,50,60]])

